### ISSUE TITLE
Files missing

### ISSUE THREAD

**Issue by Ycblue** [liyues/PatRecon#1]
Hi, 
first of all, thanks for making your code public! 
I have been reading your paper and wanted to try using your code, but the `exp` folder seems to be missing and also a `3D_CT.bin` file. 

I would really appreciate it, if you can help me get it running, or tell me how to replace the data the model needs!

**Comment by FalconMadhab** [comment]
Hi,
Thanks for the repo.
Can you provide the missing files?

**Comment by liyues** [comment]
Hi, 
We have updated the links for the model and data. Please let me know if there is other question. Thanks.

**Comment by yinyin-llll** [comment]
hi，i also want to retrain the model but it need the csv file with annotation.Do you know this file or how to design this file?
Thank you very much!
