### ISSUE TITLE
Data augmentation method in the paper

### ISSUE THREAD

**Issue by Garyline** [liyues/PatRecon#2]
Greeting!
We want to reproduce the experimental results of the paper. We used 147-layer 128*128 lung CT and found that different data augmentation methods have a great impact on the SSIM results. Now we use rotation ±2.5 degrees and displacement ±0.75 pixels. In the final test, the SSIM value can only reach 0.73, but the SSIM can reach 0.80 by only rotating ±5 degrees, all using the original network.
We want to know the data augmentation method in detail.

**Comment by liyues** [comment]
Hi, Thanks for your interests. We agree the data augmentation is important in the method. As described in the Method section of the paper, we use the translation, rotation and deformation in the data augmentation. The rotation degree is ±5 degrees which is clinically relevant, and the rotation is introduced along both the superior-inferior and the anterior-posterior directions.  The deformation field is derived from other patients' CT image. Please let me know if you have any other question. Thanks.
