### ISSUE TITLE
Can we have a discussion?

### ISSUE THREAD

**Issue by haonanxiao95** [liyues/PatRecon#4]
Dear Dr. Shen,

I am Haonan Xiao, a Ph.D. student from Prof. Jing Cai's group at The Hong Kong Polytechnic University. Our group read your paper about volumetric image reconstruction from 2D projections and we think it is very interesting and inspiring. It would be great if we can have further discussion on it, however, I cannot find your contact information. I really appreciate it if you can leave me a message at haonan.xiao@connect.polyu.hk. 

Thank you!

Best,
Haonan Xiao | 肖昊男
Ph.D. Student
Department of Health Technology and Informatics (HTI)
The Hong Kong Polytechnic University

**Comment by liyues** [comment]
Hi Haonan, 
Thanks for your interests. I am happy to discuss. My email is: liyues@stanford.edu. Please feel free to reach out. Thanks.
